name: Build Docs
description: Build MkDocs site and upload as artifact
inputs:
  python-version:
    description: Python version
    default: '3.12'
  retention-days:
    description: Artifact retention (days) for non-PR runs
    default: '7'
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install MkDocs toolchain
      shell: bash
      run: python -m pip install -r docs/requirements.txt

    - name: Build MkDocs
      shell: bash
      run: mkdocs build --strict -f docs/mkdocs.yml -d out/docs

    # Upload only when NOT a PR (saves Actions storage on PR checks)
    - name: Upload docs bundle
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v4
      with:
        name: site-docs
        path: out/docs
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: error
