version: 2

project_name: nanovision
dist: bin

builds:
  # --- macOS ---
  - id: darwin-amd64
    binary: nanovision
    main: ./cmd/main.go
    goos: [darwin]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
      - CC=zig cc -target x86_64-macos
      - CXX=zig c++ -target x86_64-macos
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: darwin-arm64
    binary: nanovision
    main: ./cmd/main.go
    goos: [darwin]
    goarch: [arm64]
    env:
      - CGO_ENABLED=0
      - CC=zig cc -target aarch64-macos
      - CXX=zig c++ -target aarch64-macos
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  # --- Linux ---
  - id: linux-amd64
    binary: nanovision
    main: ./cmd/main.go
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu
      - CXX=zig c++ -target x86_64-linux-gnu
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: linux-arm64
    binary: nanovision
    main: ./cmd/main.go
    goos: [linux]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-gnu
      - CXX=zig c++ -target aarch64-linux-gnu
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  # --- Windows ---
  - id: windows-amd64
    binary: nanovision
    main: ./cmd/main.go
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows-gnu
      - CXX=zig c++ -target x86_64-windows-gnu
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: windows-arm64
    binary: nanovision
    main: ./cmd/main.go
    goos: [windows]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-windows-gnu
      - CXX=zig c++ -target aarch64-windows-gnu
    flags:
      - -mod=vendor
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    # use zip for windows
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
