package diff

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"regexp"
	"strconv"
	"strings"
	"unicode/utf16"
)

var (
	gitDiffRE = regexp.MustCompile(`^diff --git a/(.*) b/(.*)$`)
	// fileHeaderRE captures the prefix (--- or +++) and the rest of the line
	fileHeaderRE = regexp.MustCompile(`^(\+\+\+|---)\s+(.*)$`)
	newFileRE    = regexp.MustCompile(`^new file mode \d+$`)
	hunkHeaderRE = regexp.MustCompile(`^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@.*$`)
	// ansiColorRE is a basic regex to strip ANSI escape codes if we want to try cleaning
	ansiColorRE = regexp.MustCompile(`\x1b\[[0-9;]*m`)
)

// Parse reads a unified diff file from the given path and returns a structured
// representation of its contents. It handles standard git diff format including
// file additions, modifications, and the individual hunks within each file.
//
// It automatically detects and decodes UTF-16 (LE/BE) files often generated by
// tools like Perforce or PowerShell redirects.
func Parse(path string, logger *slog.Logger) (*DiffData, error) {
	if logger == nil {
		logger = slog.Default()
	}

	// Read the entire file to check for BOMs and decode if necessary
	rawBytes, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading diff file: %w", err)
	}

	logger.Debug("Starting diff parse", "path", path, "file_size", len(rawBytes))

	content, err := decodeFileContent(rawBytes, logger)
	if err != nil {
		return nil, fmt.Errorf("decoding file content: %w", err)
	}

	// Create a reader from the decoded UTF-8 string
	reader := bufio.NewReader(strings.NewReader(content))
	data := &DiffData{}
	var currentFile *FileDiff
	var currentHunk *Hunk
	var pendingRemovals int
	var currentFileCreatedViaDiffGit bool

	for {
		lineBytes, err := reader.ReadBytes('\n')
		line := strings.TrimSuffix(string(lineBytes), "\n")
		line = strings.TrimSuffix(line, "\r")

		// Strip ANSI color codes if present (common in P4/Git output captured from terminal)
		if strings.Contains(line, "\x1b") {
			stripped := ansiColorRE.ReplaceAllString(line, "")
			if stripped != line {
				logger.Debug("Stripped ANSI color codes", "original_len", len(line), "new_len", len(stripped))
				line = stripped
			}
		}

		if line == "" && err == nil {
			// If line is empty but not EOF, just skip.
			// If err is EOF, we will handle breaking at the end of loop.
			goto nextIteration
		}

		// Parse git diff header: "diff --git a/path b/path"
		if matches := gitDiffRE.FindStringSubmatch(line); matches != nil {
			if currentFile != nil {
				if currentHunk != nil {
					currentFile.Hunks = append(currentFile.Hunks, *currentHunk)
				}
				data.Files = append(data.Files, *currentFile)
			}

			oldPath := strings.TrimPrefix(matches[1], "a/")
			newPath := strings.TrimPrefix(matches[2], "b/")

			logger.Debug("Diff found file", "raw_old", matches[1], "raw_new", matches[2])

			currentFile = &FileDiff{
				OldPath: oldPath,
				NewPath: newPath,
				Kind:    "modified",
			}
			currentHunk = nil
			currentFileCreatedViaDiffGit = true
			goto nextIteration
		}

		// Detect file additions via "new file mode" marker
		if newFileRE.MatchString(line) {
			if currentFile != nil {
				currentFile.Kind = "added"
				currentFile.OldPath = "/dev/null"
				logger.Debug("Diff file marked as added", "file", currentFile.NewPath)
			}
			goto nextIteration
		}

		// Log if we see a potential file header that isn't matching the Regex.
		if strings.HasPrefix(line, "---") || strings.HasPrefix(line, "+++") {
			if !fileHeaderRE.MatchString(line) {
				logger.Warn("Line starts with file marker but failed regex match",
					"line", line,
					"hex", fmt.Sprintf("%x", line),
				)
			}
		}

		// Parse "---" and "+++" file path headers
		if matches := fileHeaderRE.FindStringSubmatch(line); matches != nil {
			prefix, rawPath := matches[1], matches[2]

			// Clean the path:
			// Perforce/Unified diffs separate path and timestamp with a tab
			pathParts := strings.Split(rawPath, "\t")
			cleanPath := strings.TrimSpace(pathParts[0])

			// Strip Perforce version suffix (e.g., file.go#3) if present (common in OldPath)
			if strings.Contains(cleanPath, "#") {
				if idx := strings.LastIndex(cleanPath, "#"); idx > 0 {
					suffix := cleanPath[idx+1:]
					if _, err := strconv.Atoi(suffix); err == nil {
						cleanPath = cleanPath[:idx]
					}
				}
			}

			if prefix == "---" {
				if currentFile != nil {
					shouldClose := false
					if len(currentFile.Hunks) > 0 {
						shouldClose = true
					} else if !currentFileCreatedViaDiffGit && currentFile.NewPath != "" {
						shouldClose = true
					}

					if shouldClose {
						if currentHunk != nil {
							currentFile.Hunks = append(currentFile.Hunks, *currentHunk)
							currentHunk = nil
						}
						data.Files = append(data.Files, *currentFile)
						currentFile = nil
						currentFileCreatedViaDiffGit = false
					}
				}

				if currentFile == nil {
					currentFile = &FileDiff{Kind: "modified"}
					currentFileCreatedViaDiffGit = false
				}

				if cleanPath == "/dev/null" {
					currentFile.Kind = "added"
				}
				// Git style stripping (only if it starts with a/)
				currentFile.OldPath = strings.TrimPrefix(cleanPath, "a/")
			} else {
				// prefix == "+++"
				if currentFile == nil {
					// Should not happen in valid diffs, but handle gracefully
					currentFile = &FileDiff{Kind: "modified"}
				}
				// Git style stripping (only if it starts with b/)
				currentFile.NewPath = strings.TrimPrefix(cleanPath, "b/")
			}

			logger.Debug("Parsed diff header", "prefix", prefix, "raw", rawPath, "clean", cleanPath)
			goto nextIteration
		}

		// Parse hunk header: "@@ -1,5 +1,6 @@"
		if strings.HasPrefix(line, "@@ ") && strings.Contains(line, " @@") {
			if !hunkHeaderRE.MatchString(line) {
				logger.Warn("Malformed hunk header found", "line", line)
				goto nextIteration
			}
			matches := hunkHeaderRE.FindStringSubmatch(line)
			if currentFile == nil {
				logger.Error("Hunk header found without active file", "line", line)
				goto nextIteration
			}
			if currentHunk != nil {
				currentFile.Hunks = append(currentFile.Hunks, *currentHunk)
			}
			oldStart, _ := strconv.Atoi(matches[1])
			oldLines, _ := strconv.Atoi(matches[2])
			if matches[2] == "" {
				oldLines = 1
			}
			newStart, _ := strconv.Atoi(matches[3])
			newLines, _ := strconv.Atoi(matches[4])
			if matches[4] == "" {
				newLines = 1
			}

			pathForLog := "unknown"
			if currentFile != nil {
				pathForLog = currentFile.NewPath
			}
			logger.Debug("Diff found hunk", "file", pathForLog, "new_start", newStart, "new_lines", newLines)

			currentHunk = &Hunk{
				OldStart: oldStart,
				OldLines: oldLines,
				NewStart: newStart,
				NewLines: newLines,
				content:  "",
			}
			pendingRemovals = 0
			goto nextIteration
		}

		// Process hunk content lines (-, +, and context lines)
		if currentHunk != nil {
			switch {
			case strings.HasPrefix(line, "-"):
				pendingRemovals++
			case strings.HasPrefix(line, "+"):
				currentLineOffset := 0
				for _, prevLine := range strings.Split(currentHunk.content, "\n") {
					if prevLine == "" {
						continue
					}
					if strings.HasPrefix(prevLine, " ") || strings.HasPrefix(prevLine, "+") {
						currentLineOffset++
					}
				}
				if pendingRemovals > 0 {
					pendingRemovals--
				}
				currentHunk.AddedLineOffsets = append(currentHunk.AddedLineOffsets, currentLineOffset)
				currentHunk.content += line + "\n"
			case strings.HasPrefix(line, " "):
				currentHunk.content += line + "\n"
				pendingRemovals = 0
			case strings.HasPrefix(line, `\`):
				goto nextIteration
			default:
				// Only log unusual lines if they aren't empty (which loops handle)
				if strings.TrimSpace(line) != "" {
					logger.Debug("Ignoring unusual line inside a diff hunk", "line", line)
				}
			}
		} else if strings.TrimSpace(line) != "" {
			// Debug log for lines dropped outside of hunks
			logger.Debug("IGNORING LINE: No active file/hunk and line did not match headers",
				"line", line,
				"hex", fmt.Sprintf("%x", line))
		}

	nextIteration:
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			// bufio.ErrBufferFull logic can be omitted here as NewReader default size is usually sufficient
			// or ReadBytes handles resizing unless a token is too large.
			// Since we load the whole string into memory via NewReader(string),
			// ReadBytes won't actually hit BufferFull in the same way as a stream.
			return nil, fmt.Errorf("reading diff content: %w", err)
		}
	}

	// Finalize any remaining hunk and file data
	if currentHunk != nil {
		currentFile.Hunks = append(currentFile.Hunks, *currentHunk)
	}
	if currentFile != nil {
		data.Files = append(data.Files, *currentFile)
	}

	logger.Debug("Diff parse completed", "files_count", len(data.Files))
	return data, nil
}

// decodeFileContent detects BOMs (Byte Order Marks) and decodes the content to UTF-8.
func decodeFileContent(data []byte, logger *slog.Logger) (string, error) {
	if len(data) < 2 {
		return string(data), nil
	}

	// Check for UTF-16 Little Endian (FF FE)
	if data[0] == 0xFF && data[1] == 0xFE {
		logger.Debug("Detected UTF-16 LE encoding")
		return decodeUTF16(data[2:], binary.LittleEndian), nil
	}

	// Check for UTF-16 Big Endian (FE FF)
	if data[0] == 0xFE && data[1] == 0xFF {
		logger.Debug("Detected UTF-16 BE encoding")
		return decodeUTF16(data[2:], binary.BigEndian), nil
	}

	// Check for UTF-8 BOM (EF BB BF)
	if len(data) >= 3 && data[0] == 0xEF && data[1] == 0xBB && data[2] == 0xBF {
		logger.Debug("Detected UTF-8 BOM")
		return string(data[3:]), nil
	}

	// Default to UTF-8
	// Check for a NULL byte in the first 512 bytes to guess if it's binary/UTF-16 without BOM
	// (Simple heuristic, not perfect, but helps catch BOM-less UTF-16)
	checkLimit := 512
	if len(data) < checkLimit {
		checkLimit = len(data)
	}
	if bytes.IndexByte(data[:checkLimit], 0x00) != -1 {
		logger.Warn("Warning: File contains null bytes but no BOM. It might be UTF-16 without BOM, but treating as UTF-8.")
	}

	return string(data), nil
}

// decodeUTF16 converts UTF-16 byte data to a UTF-8 string
func decodeUTF16(data []byte, order binary.ByteOrder) string {
	// 2 bytes per uint16
	u16s := make([]uint16, 0, len(data)/2)
	for i := 0; i < len(data); i += 2 {
		// Ensure we have a pair of bytes
		if i+1 < len(data) {
			u16s = append(u16s, order.Uint16(data[i:i+2]))
		}
	}
	return string(utf16.Decode(u16s))
}
