import { GITHUB_URL, WEBSITE_URL } from '@/lib/consts'

export default function Footer() {
    return (
        <footer className="mt-4 border-border border-t pt-6 text-center text-muted-foreground text-sm">
            <p>
                Generated by{' '}
                <a
                    href={GITHUB_URL}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="font-medium text-primary hover:underline"
                >
                    nanovision
                </a>
            </p>
            <div className="mt-2 flex items-center justify-center gap-4">
                <a href={WEBSITE_URL} target="_blank" rel="noopener noreferrer" className="hover:underline">
                    Website
                </a>
                <a href={GITHUB_URL} target="_blank" rel="noopener noreferrer" className="hover:underline">
                    GitHub
                </a>
                <a href={GITHUB_URL} target="_blank" rel="noopener noreferrer" className="hover:underline">
                    Sponsor
                </a>
            </div>
        </footer>
    )
}
