import { CheckCircle2, Flame, XCircle } from 'lucide-react'
import { useMemo } from 'react'
import DiffStatusBadge from '@/components/DiffStatusBadge'
import { cn } from '@/lib/utils'
import type { FileNode, Review } from '@/lib/validation'
import type { DiffStatus } from '@/types/summary'

interface ReviewSummaryProps {
    review: Review
    /** Flat node list, used to resolve a hotspot's file to its details page URL. */
    nodes: FileNode[]
}

const formatPct = (value: number) => `${value.toFixed(1)}%`

/**
 * The review-mode header: gate verdict banner, changelist stat cards and the
 * risk-hotspot table. Rendered by SummaryPage only when the report carries a
 * `review` block (i.e. it was generated by the HtmlReview report type).
 */
export default function ReviewSummary({ review, nodes }: ReviewSummaryProps) {
    const { stats, checks = [], hotspots = [] } = review
    const failedChecks = checks.filter((c) => !c.passed)

    const urlByPath = useMemo(() => {
        const map = new Map<string, string>()
        for (const node of nodes) {
            if (node.type === 'file' && node.targetUrl) map.set(node.path, node.targetUrl)
        }
        return map
    }, [nodes])

    const patchPct =
        stats.patchStatementsValid > 0 ? (100 * stats.patchStatementsCovered) / stats.patchStatementsValid : null
    const patchCheck = checks.find((c) => c.key === 'patch_statement_coverage')
    const complexityCheck = checks.find((c) => c.key === 'max_changed_method_complexity')
    const methodsTouched = stats.methodsAdded + stats.methodsModified

    return (
        <div className="mb-4 flex flex-col gap-4">
            {checks.length > 0 && (
                <div
                    className={cn(
                        'flex items-start gap-2 rounded-md border p-3 text-sm',
                        review.passed
                            ? 'border-covered/40 bg-covered/10 text-covered'
                            : 'border-uncovered/40 bg-uncovered/10 text-uncovered',
                    )}
                >
                    {review.passed ? (
                        <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" />
                    ) : (
                        <XCircle className="mt-0.5 h-4 w-4 shrink-0" />
                    )}
                    <div>
                        <div className="font-semibold">
                            {review.passed ? 'Review gate passed' : 'Review gate failed'}
                        </div>
                        {failedChecks.length > 0 && (
                            <ul className="mt-1 list-inside list-disc">
                                {failedChecks.map((check) => (
                                    <li key={check.key}>
                                        {check.label} is {check.value.toFixed(1)} (limit {check.threshold.toFixed(1)})
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>
                </div>
            )}

            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
                <StatCard
                    label="Patch statement coverage"
                    value={patchPct === null ? 'n/a' : formatPct(patchPct)}
                    hint={
                        stats.patchStatementsValid > 0
                            ? `${stats.patchStatementsCovered} / ${stats.patchStatementsValid} statements`
                            : 'no coverable changed statements'
                    }
                    tone={patchCheck ? (patchCheck.passed ? 'good' : 'bad') : 'neutral'}
                />
                <StatCard label="Changed files" value={String(stats.changedFiles)} hint="in this changelist" />
                <StatCard
                    label="Methods touched"
                    value={String(methodsTouched)}
                    hint={`${stats.methodsAdded} added, ${stats.methodsModified} modified`}
                />
                <StatCard
                    label="Untested changed methods"
                    value={String(stats.untestedChangedMethods)}
                    hint="changed code, zero coverage"
                    tone={stats.untestedChangedMethods > 0 ? 'bad' : 'good'}
                />
                <StatCard
                    label="Max changed complexity"
                    value={String(stats.maxChangedComplexity)}
                    hint="highest CC among changed methods"
                    tone={complexityCheck ? (complexityCheck.passed ? 'good' : 'bad') : 'neutral'}
                />
            </div>

            {hotspots.length > 0 && (
                <div className="overflow-hidden rounded-md border border-border bg-card">
                    <div className="flex items-center gap-2 border-border border-b bg-muted/40 px-3 py-2">
                        <Flame className="h-4 w-4 shrink-0 text-partial" />
                        <span className="font-semibold text-sm">Review hotspots</span>
                        <span className="text-muted-foreground text-xs">
                            changed methods ranked by risk (complexity × untested)
                        </span>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="text-left text-muted-foreground text-xs">
                                    <th className="px-3 py-1.5 font-medium">Method</th>
                                    <th className="px-3 py-1.5 font-medium">File</th>
                                    <th className="px-2 py-1.5 text-center font-medium">Change</th>
                                    <th className="px-2 py-1.5 text-right font-medium">Complexity</th>
                                    <th className="px-2 py-1.5 text-right font-medium">Patch coverage</th>
                                    <th className="px-3 py-1.5 text-right font-medium">Risk</th>
                                </tr>
                            </thead>
                            <tbody>
                                {hotspots.map((h) => {
                                    const url = urlByPath.get(h.file)
                                    const location = `${h.file}:${h.startLine}`
                                    return (
                                        <tr
                                            key={`${h.file}-${h.startLine}-${h.method}`}
                                            className="border-border border-t hover:bg-muted/40"
                                        >
                                            <td
                                                className="max-w-64 truncate px-3 py-1.5 font-mono text-xs"
                                                title={h.method}
                                            >
                                                {h.method}
                                            </td>
                                            <td
                                                className="max-w-72 truncate px-3 py-1.5 font-mono text-xs"
                                                title={location}
                                            >
                                                {url ? (
                                                    <a href={url} className="text-primary hover:underline">
                                                        {location}
                                                    </a>
                                                ) : (
                                                    <span className="text-muted-foreground">{location}</span>
                                                )}
                                            </td>
                                            <td className="px-2 py-1.5 text-center">
                                                <DiffStatusBadge status={h.diffStatus as DiffStatus} />
                                            </td>
                                            <td className="px-2 py-1.5 text-right tabular-nums">
                                                {h.complexity !== undefined ? h.complexity.toFixed(0) : '—'}
                                            </td>
                                            <td
                                                className={cn(
                                                    'px-2 py-1.5 text-right tabular-nums',
                                                    h.patchCoverage !== undefined &&
                                                        h.patchCoverage < 50 &&
                                                        'text-uncovered',
                                                    h.patchCoverage !== undefined &&
                                                        h.patchCoverage >= 50 &&
                                                        h.patchCoverage < 80 &&
                                                        'text-partial',
                                                )}
                                            >
                                                {h.patchCoverage !== undefined ? formatPct(h.patchCoverage) : '—'}
                                            </td>
                                            <td className="px-3 py-1.5 text-right font-semibold tabular-nums">
                                                {h.risk.toFixed(1)}
                                            </td>
                                        </tr>
                                    )
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}
        </div>
    )
}

function StatCard({
    label,
    value,
    hint,
    tone = 'neutral',
}: {
    label: string
    value: string
    hint?: string
    tone?: 'neutral' | 'good' | 'bad'
}) {
    return (
        <div className="rounded-md border border-border bg-card p-3">
            <div className="text-muted-foreground text-xs">{label}</div>
            <div
                className={cn(
                    'font-semibold text-xl tabular-nums',
                    tone === 'good' && 'text-covered',
                    tone === 'bad' && 'text-uncovered',
                )}
            >
                {value}
            </div>
            {hint && <div className="mt-0.5 text-[11px] text-muted-foreground">{hint}</div>}
        </div>
    )
}
