site_name: nanovision Docs
site_url: https://igorbayerl.github.io/nanovision/

repo_url: https://github.com/igorbayerl/nanovision
repo_name: igorbayerl/nanovision
edit_uri: edit/main/docs/
theme:
  logo: imgs/icon.png
  favicon: imgs/icon.ico
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: lime

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.superfences

nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Project Roadmap':
    - 'Overview': 'roadmap/index.md'
    - 'New HTML Reporter (React)':
      - 'Overview': 'roadmap/new-react-reporter/index.md'
      - 'Motivation & Architecture': 'roadmap/new-react-reporter/feature-plan-ssr-react-islands.md'
      - 'File Page Refactor Plan': 'roadmap/new-react-reporter/feature-plan-file-page-refactor.md'
      - 'Summary Page Refactor Plan': 'roadmap/new-react-reporter/feature-plan-summary-page-refactor.md'
      - 'UI Development Guide': 'roadmap/new-react-reporter/ui-development-guide.md'
    - 'Hierarchical Components': 'roadmap/components.md'
    - 'Traceable Reports': 'roadmap/trace-reports.md'
    - 'Live Reload (Watch Mode)': 'roadmap/watch-mode.md'
  - 'Contributing': 'contributing.md'