name: PR Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'docs/**'
      - 'scripts/**'
      - 'docs/requirements.txt'
      - '.github/actions/**'
      - '.github/workflows/pr_checks.yml'

permissions:
  contents: read

concurrency:
  group: pr-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-docs

  build_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-report
