name: Publish to Winget

on:
  release:
    types: [published]

jobs:
  winget:
    name: Publish to Winget
    runs-on: ubuntu-latest
    steps:
      - name: Submit to Winget
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: IgorBayerl.nanovision
          token: ${{ secrets.WINGET_TOKEN }}
